# Generated by Django 5.2.1 on 2025-05-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='title',
        ),
    ]
