# Generated by Django 5.2.1 on 2025-05-21 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_postfile_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='contentuserprofile',
            name='last_activity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='comment_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='content.postcomment'),
        ),
    ]
