# Generated by Django 5.2.1 on 2025-05-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_post_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentuserprofile',
            name='full_name',
        ),
    ]
